AWSTemplateFormatVersion: '2010-09-09'
Description: 'Options Watchdog v2

  '
Globals:
  Function:
    Environment:
      Variables:
        CONCURRENCY_SIZE: 5
        DEBUG: 0
    MemorySize: 512
    Timeout: 30
Outputs:
  OptionsDeleteAPI:
    Description: API Gateway endpoint URL for Prod stage for Expired Options function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/optionsDeletev2/{optionsKey}
  OptionsDeleteFunction:
    Description: Delete Options
    Value:
      Fn::GetAtt:
      - OptionsDeleteFunction
      - Arn
  OptionsDeleteFunctionIamRole:
    Description: Implicit IAM Role created for expired options function
    Value:
      Fn::GetAtt:
      - OptionsDeleteFunctionRole
      - Arn
  OptionsExpiredAPI:
    Description: API Gateway endpoint URL for Prod stage for Expired Options function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/optionsExpiredv2/
  OptionsExpiredFunction:
    Description: Expired Options
    Value:
      Fn::GetAtt:
      - OptionsExpiredFunction
      - Arn
  OptionsExpiredFunctionIamRole:
    Description: Implicit IAM Role created for expired options function
    Value:
      Fn::GetAtt:
      - OptionsExpiredFunctionRole
      - Arn
  OptionsModApi:
    Description: API Gateway endpoint URL for Prod stage for options mod v2 function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/optionsModv2/
  OptionsModFunction:
    Description: Options Mod Function ARN
    Value:
      Fn::GetAtt:
      - OptionsModFunction
      - Arn
  OptionsModIamRole:
    Description: Implicit IAM Role created for Options Mod function
    Value:
      Fn::GetAtt:
      - OptionsModFunctionRole
      - Arn
  OptionsSummaryAPI:
    Description: API Gateway endpoint URL for Prod stage for summary Options function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/optionsSummaryv2/
  OptionsSummaryFunction:
    Description: Options Summary
    Value:
      Fn::GetAtt:
      - OptionsSummaryFunction
      - Arn
  OptionsSummaryFunctionIamRole:
    Description: Implicit IAM Role created for summary options function
    Value:
      Fn::GetAtt:
      - OptionsSummaryFunctionRole
      - Arn
  OptionsWatchdogApi:
    Description: API Gateway endpoint URL for Prod stage for options watchdog v2 function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/optionsWatchdogv2/
  OptionsWatchdogFunction:
    Description: Options Watchdog Function ARN
    Value:
      Fn::GetAtt:
      - OptionsWatchdogFunction
      - Arn
  OptionsWatchdogIamRole:
    Description: Implicit IAM Role created for Options Watchdog function
    Value:
      Fn::GetAtt:
      - OptionsWatchdogFunctionRole
      - Arn
Resources:
  OptionsDeleteFunction:
    Properties:
      CodeUri: s3://larsbucket1/a4e3b153e8649306755d9f2f310a1e73
      Events:
        OptionsMod:
          Properties:
            Auth:
              ApiKeyRequired: true
            Method: delete
            Path: /optionsDeletev2/{optionsKey}
          Type: Api
      Handler: optionsDelExp.deleteOptions_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
  OptionsExpiredFunction:
    Properties:
      CodeUri: s3://larsbucket1/dc07a113219a89cdcf5403e156a513d1
      Events:
        OptionsMod:
          Properties:
            Auth:
              ApiKeyRequired: true
            Method: get
            Path: /optionsExpiredv2
          Type: Api
      Handler: optionsDelExp.expiredOptions_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
  OptionsModFunction:
    Properties:
      CodeUri: s3://larsbucket1/0d7ed5bff3e622a18269351e96440c28
      Events:
        OptionsMod:
          Properties:
            Auth:
              ApiKeyRequired: true
            Method: post
            Path: /optionsModv2
          Type: Api
      Handler: optionsMod.lambda_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
  OptionsSummaryFunction:
    Properties:
      CodeUri: s3://larsbucket1/05b465d67cd38437dea567b41a4fe5b2
      Events:
        OptionsMod:
          Properties:
            Auth:
              ApiKeyRequired: true
            Method: get
            Path: /optionsSummaryv2
          Type: Api
      Handler: optionsSummary.lambda_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
  OptionsWatchdogFunction:
    Properties:
      CodeUri: s3://larsbucket1/0296ddd0eac9f30b6cd228d0d7cc5f2e
      Events:
        OptionsWatchdog:
          Properties:
            Auth:
              ApiKeyRequired: true
            Method: get
            Path: /optionsWatchdogv2
          Type: Api
      Handler: optionsWatchdog.lambda_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
